name: validate
on:
  push:
    branches:
      - test

jobs:
  build-rom:
    runs-on: ubuntu-latest
    steps:
      - name: Create cache for docker image
        uses: actions/cache@v4
        with:
          path: rom
          key: basefile
      - name: Setup dependencies
        run: |
          mkdir -p rom
          cd rom
          pwd
          echo "my first file" > file.txt
          ls -al .
          cat file.txt
        
  build-unix:
    needs: build-rom
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      volumes: 
      - /home/runner/work/Zelda64Recomp/Zelda64Recomp:/mm
    steps:
      - name: Restore cached docker image
        uses: actions/cache/restore@v4
        with:
          path: rom
          key: basefile
      - name: Setup dependencies
        run: |
          pwd
          ls -al .
          ls -al /
          ls -al /mm
          ls -al /home/runner
          echo "done"
