name: validate
on:
  push:
    branches:
      - test

jobs:
  build-rom:
    runs-on: ubuntu-latest
    steps:
      - name: Setup dependencies
        run: |
          pwd
          echo "my first file" > file.txt
          ls -al .
          cat file.txt
        
  build-unix:
    needs: build-rom
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      volumes: 
      - /workspace:/github/workspace
    steps:
      - name: Setup dependencies
        run: |
          pwd
          ls -al .
